name: Test Action

on:
  push:
    branches : [main]

jobs:
 build:

  runs-on: ubuntu-latest
  
  steps:
     - uses: actions/checkout@v2
     - uses: actions/setup-node@v2
       with:
         node-version : 16
     - name: check commands
       run:  pwd
       
     - name: check ls
       run:  ls
       
     - name: Install surge
       run:  npm install -g surge
       
     - name: Deploy website on surge
       run:  surge ./ adhesive-joke.surge.sh --token ${{secrets.SURGE_LOGIN}}
